### ISSUE TITLE
Coworker doesn't work on zeebe client 8.4.1

### ISSUE THREAD

**Issue by ivsokol** [camunda-community-hub/kotlin-coworker#90]
Hi,

I am trying to connect to zeebe version 8.4.1 with coworker and upload DMN resource.
Connection works, but when I try to upload resource like this

test("should upload resources") {
        ZeebeClientSingleton.zeebeClient
            .newDeployResourceCommand()
            .addResourceFromClasspath("/gsm.dmn")
            .send()
            .join()
    }

it returns this error

`
'io.camunda.zeebe.gateway.protocol.GatewayOuterClass$DeployResourceRequest$Builder io.camunda.zeebe.gateway.protocol.GatewayOuterClass$DeployResourceRequest$Builder.setTenantId(java.lang.String)'
java.lang.NoSuchMethodError: 'io.camunda.zeebe.gateway.protocol.GatewayOuterClass$DeployResourceRequest$Builder io.camunda.zeebe.gateway.protocol.GatewayOuterClass$DeployResourceRequest$Builder.setTenantId(java.lang.String)'
	at io.camunda.zeebe.client.impl.command.DeployResourceCommandImpl.tenantId(DeployResourceCommandImpl.java:197)
	at io.camunda.zeebe.client.impl.command.DeployResourceCommandImpl.<init>(DeployResourceCommandImpl.java:65)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.newDeployResourceCommand(ZeebeClientImpl.java:291)
	at hr.ht.rnd.sandbox.zeebe.UploadResources$1$1.invokeSuspend(UploadResources.kt:14)
`

In my build.gradle I am forcing zeebe.client to use version 8.4.1

Problem is that zeebe-coworker uses version 8.2.7 and in version 8.4.1 there is no longer  method setTenantId().

I pulled locally your main branch, updated zeebe.version in https://github.com/camunda-community-hub/kotlin-coworker/blob/a64f6e966fed5949f39a5f93c8e99235d28be7c3/pom.xml#L40 to 8.4.1 and all tests are passing.

Can you please update zeebe.version and publish new version of library (0.5.1 presumably)?

Kind regards,
Ivan Sokol

**Comment by aivinog1** [comment]
Hello @ivsokol!
First of all - thank you for trying out Coworkers ⭐ 

But, unfortunately, I can't reproduce the issue: https://github.com/aivinog1/kotlin-coworker/commit/2f585e1f057b81e9a43cc914f50cba54649f2ef2 (the test is positive)

I am positive about updating to the new version of the Zeebe Client, but it is not so easy task right now 🙁 Could you please provide a minimum reproducible example of the issue I would be glad to help 🙂

**Comment by ivsokol** [comment]
Hi, I created demo project which you can pull and check for yourself (instructions are in readme)
https://github.com/ivsokol/coworker-demo.git  

I based it on Testcontainers to run zeebe locally and I used public DMN that I am trying to upload to Zeebe.

Also, why upgrade to latest version of zeebe client is complex? I tried pulling your code, updating zeebe.version in pom and running tests again, it is all passing.

Thanks for the support,
Ivan Sokol

**Comment by ivsokol** [comment]
Hi,

did you managed to recreate an issue?
